### PR TITLE
Fix loading of mailing view page for anonymous users

### LINKED ISSUE #29: Syntax Error when view mailing in browser
DB syntax error occurred when mailing is views by anonymous user.

'view public CiviMail content' permission granted to anonymous role, user no longer need to access to open email in browser. (e.g. View in your browser => domainname/civicrm/mailing/view?reset=1&id=255)
we have [page_callback](https://github.com/civicrm/org.civicrm.flexmailer/blame/master/flexmailer.php#L199) replacement using this extension. which required contact id.

since, its anonymous user. No contact id present and get DB error.

We are using civicrm 4.7.31 version

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Fixes https://github.com/civicrm/org.civicrm.flexmailer/issues/29

Mailing view page now uses flexmailing preview API to view the mailing which displays a DB error for anonymous users.

The function `getContactNames()` seems to return an empty array if it does not find any contact in the `$ids` variable. 

The condition `if (!$ids) {` does not seem to work if `$task->getContactId()` returns an empty string. Moved the `array_filter` just above the check and it works fine now.

### CODE REVIEW

File: src/Listener/ToHeader.php [hunk 1]
```diff
@@ -70,11 +70,12 @@ protected function getContactNames($tasks) {
       $ids[$task->getContactId()] = $task->getContactId();
     }
 
+    $ids = array_filter($ids, 'is_numeric');
     if (!$ids) {
```
Comment (yashodha) [inline src/Listener/ToHeader.php]: @jitendrapurohit 
should we do  `if (!empty($ids)) {` instead?

Comment (totten) [reply src/Listener/ToHeader.php]: Thanks @jitendrapurohit! I can confirm that patch resolves the crash when opening `civicrm/mailing/view` anonymously. Nice.

I also share @yashodha's sense that `empty()` is better than implicitly casting to a boolean. I'm not really sure why, and it fixes either way, but it's easy to tack on an extra commit for that.

Rebased+merged.

**Comment by reecebenson** [comment]
Hi all,

Using the latest master version on a client's site who was having an issue with this particular scenario, however still having issues viewing the mailing as an anonymous user.

Visiting this URL:
`https://SITENAME/civicrm/mailing/view?reset=1&id=1614`

Stacktrace:
```
#0 /var/sites/SITENAME/civicrm_extensions/org.civicrm.flexmailer/src/Page/ViewMailing.php(43): civicrm_api3("Mailing", "preview", (Array:2))
#1 /var/www/drupal758civi5103/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): Civi\FlexMailer\Page\ViewMailing->run((Array:3), NULL)
#2 /var/www/drupal758civi5103/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#3 /var/www/drupal758civi5103/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#4 /var/www/drupal758civi5103/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#5 /var/www/drupal758civi5103/includes/menu.inc(527): civicrm_invoke("mailing", "view")
#6 /var/www/drupal758civi5103/index.php(21): menu_execute_active_handler()
#7 {main}
```

Commenting here as @totten mentioned this addressed the problem, however the issue persists for me. (Also, ensured that I have the latest version of the `master` branch by doing a git log, latest commit hash is [61b2fb9](https://github.com/civicrm/org.civicrm.flexmailer/commit/61b2fb9b0ead0946caa6c854d8861980a0781261))

**Comment by seamuslee001** [comment]
@reecebenson you may want to try applying the changes here https://github.com/civicrm/civicrm-core/pull/14162 and https://github.com/civicrm/org.civicrm.flexmailer/pull/38

**Comment by totten** [comment]
@reecebenson yep, thanks for commenting. I've re-opened issue #29.

In follow-up testing, I found that #33 fixes the error in a few circumstances (e.g. if the mailing has `template_type=mosaico` or if you configure the [new setting](https://github.com/civicrm/org.civicrm.flexmailer/pull/37) `flexmailer_traditional=flexmailer`), but there's still an error with `traditional` mailings in a default configuration. Hence the reopened issue.
